#+TITLE: README
#+PROPERTY: header-args :session README
* setup
* .env
We use =.env= files to keep track of machine-specific variables. Create a
=.env= in the root of this project with the following values set:
#+BEGIN_EXAMPLE sh
PROJECT_DIR=/path/to/root/of/project/
DATA_DIR=/path/to/root/of/project/data/
SRC_DIR=/path/to/src/dir/ # where to install any packages from source
#+END_EXAMPLE
To access these variables in python code run:
#+BEGIN_SRC python
from decouple import config
config("PROJECT_DIR")
#+END_SRC


* virtualenv
Initialize a virtualenv in python3.8
#+BEGIN_SRC sh
virtualenv ~/.virtualenvs/pcam --python=python3.8
source ~/.virtualenvs/pcam/bin/activate
#+END_SRC
** pytorch
Install pytorch using the following command (but look at https://pytorch.org/
if you're not using Linux).
#+begin_SRC sh
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
#+END_SRC
** wandb
Set up an [[https://docs.wandb.ai/quickstart#1.-set-up-wandb][wandb]] account on. To setup wandb, run:
#+BEGIN_SRC sh
pip install wandb
wandb login
#+END_SRC
** custom code
Run the following to install the contents under =src/= as a package:
#+BEGIN_SRC sh
pip install -e .
#+END_SRC
** other requirements
After having run this, install the rest of the requirements using:
#+BEGIN_SRC sh
pip install -r requirements.txt
#+END_SRC
* data
Download [[https://drive.google.com/drive/folders/1gHou49cA1s5vua2V5L98Lt8TiWA3FrKB][this drive folder]] as a =.zip=. Move out of the folder, right click on
this folder, and select =Download=. This will download both a =.zip= and a
=.gz= named like =pcamv1-<timestamp>-001.zip= and =*gz=. The =.gz= file is
likely to fail as it is too big. You can use [[https://drive.google.com/file/d/1Ka0XfEMiwgCYPdTI-vv6eUElOBnKFKQ2/view][this link]] to download it
separately.

Find the exact names of the files and run the following:
#+BEGIN_SRC sh
source .env
mkdir -p $DATA_DIR
unzip ~/Downloads/pcamv1-20220914T134745Z-001.zip -d $DATA_DIR/ # change the exact name of the file here
#mv ~/Downloads/ add .gz instructions
#+END_SRC

